### ISSUE TITLE
Changing the configuration of the beautiful logger should also change the configuration of underlying logger

### ISSUE THREAD

**Issue by tokazio** [forax/beautiful_logger#5]
```
LoggerConfig.fromPackage("com.esyo.sharedesk.channels").update(opt -> {
            opt.enable(true);
            opt.level(Level.DEBUG);
        });
```
N'affiche pas les messages de .debug(), j'ai bien les .info()

+

Comment je peux utiliser log4j (et log4j.properties) stp?

**Comment by forax** [comment]
beautiful_logger acts as a facade, so there are two levels, the level of the beautiful logger and the level of Log4J. So to log something both levels need to be at a level that allows logging.

I agree that the current behavior seems wrong, the configuration level of the beautiful logger should be in sync with the configuration level of the underlying logger at least if the change to configuration is always done through the beautiful logger API (LoggerConfig).

I will fix that !

**Comment by forax** [comment]
Fixed in 0.9.9,
now you can choose if you want to change the log level of the underlying logger (Log4j in your case) at the same time you change the log level of the Logger.

```
LoggerConfig.fromPackage("com.esyo.sharedesk.channels").update(opt -> opt.level(Level.DEBUG, true));
```

It doesn't work if one use SLF4J or the System.Logger because those facade doesn't allow to change the loglevel of the facaded logger.

**Comment by tokazio** [comment]
Merci :)

**Comment by tokazio** [comment]
Salut,

Je n'arrive toujours pas à afficher du debug avec log4j
`LoggerConfig.fromPackage("com.esyo.sharedesk.channels").update(opt -> opt.level(Level.DEBUG, true));`
J'ai les 'info' mais pas les 'debug'. J'utilise un log4j.properties pour configurer log4j

tu peux regarder https://bitbucket.org/tokazio/sharedesk/src/master/ si besoin, il y a peut être quelque chose que je fais mal :(

**Comment by forax** [comment]
Salut,
il faut aussi changer dans le reste du code les imports pour utiliser  com.github.forax.beautifullogger.Logger à la place du Logger de Log4J.
Le logger de beautiful logger doit être celui que tu utilises dans l'appli, en interne, il s'oocupe de parler à Log4j lorsque cela est nécessaire.

**Comment by tokazio** [comment]
Oui mais je testais pour l'instant que dans l'app serveur principale.
Même avec ta correction, LOGGER.info est bien pris en compte mais toujours pas LOGGER.debug.
