### ISSUE TITLE
Use of sun.misc.Unsafe and Java 17

### ISSUE THREAD

**Issue by a1730** [forax/beautiful_logger#7]
Hi,
Any chance of removing the use of sun.misc.Unsafe in this logger for use with Java 17?

> Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineAnonymousClass(java.lang.Class, byte[], java.lang.Object[])'
	at com.github.forax.beautifullogger.LoggerImpl.loggerClass(LoggerImpl.java:526)
	at com.github.forax.beautifullogger.LoggerImpl.<clinit>(LoggerImpl.java:519)
	at com.github.forax.beautifullogger.Logger.getLogger(Logger.java:327)
	at com.cargoio.aristax.core.BeautifulLogger.<clinit>(BeautifulLogger.java:18)

Thanks for this tiny logger.

**Comment by forax** [comment]
i should give it a try !

**Comment by a1730** [comment]
Hi @forax,
Not yo nag but did you give it a try, or I should forgitabouit?
Thanks.

**Comment by a1730** [comment]
Hi @forax,

You started looking at the issue ... yay! Thank you.

Heads up, the last few commits have been failing on jitpack ([build.log](https://javadoc.jitpack.io/com/github/forax/beautiful_logger/master-0.9.11-gc99ab51-15/build.log)) to the extent that master-SNAPSHOT tag is no longer usable.
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project beautifullogger: Fatal error compiling: invalid flag: --release -> [Help 1]

I was not sure if to report the issue here or on the [jitpack](https://github.com/jitpack/jitpack.io/issues/5093#issue-1251288540) repo - I did both.
Thank you.

**Comment by forax** [comment]
yes, i know, i'm still working on the Java 8 support :)

**Comment by forax** [comment]
I've just published the version 0.10 that should work with Java 8 to Java 18+.

https://github.com/forax/beautiful_logger/releases/tag/0.10

**Comment by a1730** [comment]
Thank you!
Downloaded and tested. The java diagnostic is gone.
THANK YOU.

**Comment by forax** [comment]
Hi, you should use the version 0.10.4, previous versions have the optional dependencies in the pom.xml not marked as optional, sorry !

**Comment by a1730** [comment]
Hi!

We noticed but decided to be grateful consumers of the library rather than whiners.
Thank you for the excellent job! I was using the packe to learn how the MH guru (YOU) would move from Unsafe to MH. Lesson learnt:)

Thank you, very much.

PS:  Javadocs are not deployed with the released package.[build-log](https://javadoc.jitpack.io/com/github/forax/beautiful_logger/0.10.5/build.log)
